# Generated by Django 4.1.5 on 2023-01-19 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=400, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('0', 'ADMIN'), ('1', 'FOOD RETAILER'), ('2', 'ORGANIZATION'), ('3', 'NGO'), ('4', 'USER')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'USER_DETAILS',
            },
        ),
    ]
