# Generated by Django 4.1.5 on 2023-01-19 23:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_userdetials_city_userdetials_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 20, 4, 30, 28, 259979), null=None)),
                ('received_status', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 20, 4, 30, 28, 259979), null=None)),
                ('donated_status', models.BooleanField(default=False)),
                ('donated_at', models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 20, 4, 30, 28, 259979), null=None)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FromUser', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DONATIONS',
            },
        ),
    ]
