# Generated by Django 4.1.5 on 2023-01-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='food_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donations',
            name='plate_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='donations',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donations',
            name='applied_at',
            field=models.DateTimeField(blank=None, null=None),
        ),
        migrations.AlterField(
            model_name='donations',
            name='donated_at',
            field=models.DateTimeField(blank=None, null=None),
        ),
        migrations.AlterField(
            model_name='donations',
            name='received_at',
            field=models.DateTimeField(blank=None, null=None),
        ),
    ]
