# Generated by Django 4.1.5 on 2023-01-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userdetials_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donations',
            name='donated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donations',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
